//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MES_Android.LoginService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoginServiceSoap", Namespace="http://LoginService.fask.cz/")]
    public partial class LoginService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetKatalogUzivateleTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKatalogUzivateleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKatalogUzivateleSPravamaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHashOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnlineLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LoginService() {
            this.Url = "http://localhost/MST_Win_Kom_Server_7_Dasenka/LoginService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetKatalogUzivateleTestCompletedEventHandler GetKatalogUzivateleTestCompleted;
        
        /// <remarks/>
        public event GetKatalogUzivateleCompletedEventHandler GetKatalogUzivateleCompleted;
        
        /// <remarks/>
        public event GetKatalogUzivateleSPravamaCompletedEventHandler GetKatalogUzivateleSPravamaCompleted;
        
        /// <remarks/>
        public event GetHashCompletedEventHandler GetHashCompleted;
        
        /// <remarks/>
        public event OnlineLoginCompletedEventHandler OnlineLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LoginService.fask.cz/GetKatalogUzivateleTest", RequestNamespace="http://LoginService.fask.cz/", ResponseNamespace="http://LoginService.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetKatalogUzivateleTest(byte idterminal) {
            object[] results = this.Invoke("GetKatalogUzivateleTest", new object[] {
                        idterminal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetKatalogUzivateleTestAsync(byte idterminal) {
            this.GetKatalogUzivateleTestAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void GetKatalogUzivateleTestAsync(byte idterminal, object userState) {
            if ((this.GetKatalogUzivateleTestOperationCompleted == null)) {
                this.GetKatalogUzivateleTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKatalogUzivateleTestOperationCompleted);
            }
            this.InvokeAsync("GetKatalogUzivateleTest", new object[] {
                        idterminal}, this.GetKatalogUzivateleTestOperationCompleted, userState);
        }
        
        private void OnGetKatalogUzivateleTestOperationCompleted(object arg) {
            if ((this.GetKatalogUzivateleTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKatalogUzivateleTestCompleted(this, new GetKatalogUzivateleTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LoginService.fask.cz/GetKatalogUzivatele", RequestNamespace="http://LoginService.fask.cz/", ResponseNamespace="http://LoginService.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject GetKatalogUzivatele(byte idterminal) {
            object[] results = this.Invoke("GetKatalogUzivatele", new object[] {
                        idterminal});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetKatalogUzivateleAsync(byte idterminal) {
            this.GetKatalogUzivateleAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void GetKatalogUzivateleAsync(byte idterminal, object userState) {
            if ((this.GetKatalogUzivateleOperationCompleted == null)) {
                this.GetKatalogUzivateleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKatalogUzivateleOperationCompleted);
            }
            this.InvokeAsync("GetKatalogUzivatele", new object[] {
                        idterminal}, this.GetKatalogUzivateleOperationCompleted, userState);
        }
        
        private void OnGetKatalogUzivateleOperationCompleted(object arg) {
            if ((this.GetKatalogUzivateleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKatalogUzivateleCompleted(this, new GetKatalogUzivateleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LoginService.fask.cz/GetKatalogUzivateleSPravama", RequestNamespace="http://LoginService.fask.cz/", ResponseNamespace="http://LoginService.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject GetKatalogUzivateleSPravama(byte idterminal, string[] prava) {
            object[] results = this.Invoke("GetKatalogUzivateleSPravama", new object[] {
                        idterminal,
                        prava});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetKatalogUzivateleSPravamaAsync(byte idterminal, string[] prava) {
            this.GetKatalogUzivateleSPravamaAsync(idterminal, prava, null);
        }
        
        /// <remarks/>
        public void GetKatalogUzivateleSPravamaAsync(byte idterminal, string[] prava, object userState) {
            if ((this.GetKatalogUzivateleSPravamaOperationCompleted == null)) {
                this.GetKatalogUzivateleSPravamaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKatalogUzivateleSPravamaOperationCompleted);
            }
            this.InvokeAsync("GetKatalogUzivateleSPravama", new object[] {
                        idterminal,
                        prava}, this.GetKatalogUzivateleSPravamaOperationCompleted, userState);
        }
        
        private void OnGetKatalogUzivateleSPravamaOperationCompleted(object arg) {
            if ((this.GetKatalogUzivateleSPravamaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKatalogUzivateleSPravamaCompleted(this, new GetKatalogUzivateleSPravamaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LoginService.fask.cz/GetHash", RequestNamespace="http://LoginService.fask.cz/", ResponseNamespace="http://LoginService.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHash(byte idterminal, string login, string password) {
            object[] results = this.Invoke("GetHash", new object[] {
                        idterminal,
                        login,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHashAsync(byte idterminal, string login, string password) {
            this.GetHashAsync(idterminal, login, password, null);
        }
        
        /// <remarks/>
        public void GetHashAsync(byte idterminal, string login, string password, object userState) {
            if ((this.GetHashOperationCompleted == null)) {
                this.GetHashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHashOperationCompleted);
            }
            this.InvokeAsync("GetHash", new object[] {
                        idterminal,
                        login,
                        password}, this.GetHashOperationCompleted, userState);
        }
        
        private void OnGetHashOperationCompleted(object arg) {
            if ((this.GetHashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHashCompleted(this, new GetHashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LoginService.fask.cz/OnlineLogin", RequestNamespace="http://LoginService.fask.cz/", ResponseNamespace="http://LoginService.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OnlineLogin(byte idterminal, int idUser, string login, string password, string hashPassword, ref int userID) {
            object[] results = this.Invoke("OnlineLogin", new object[] {
                        idterminal,
                        idUser,
                        login,
                        password,
                        hashPassword,
                        userID});
            userID = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OnlineLoginAsync(byte idterminal, int idUser, string login, string password, string hashPassword, int userID) {
            this.OnlineLoginAsync(idterminal, idUser, login, password, hashPassword, userID, null);
        }
        
        /// <remarks/>
        public void OnlineLoginAsync(byte idterminal, int idUser, string login, string password, string hashPassword, int userID, object userState) {
            if ((this.OnlineLoginOperationCompleted == null)) {
                this.OnlineLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnlineLoginOperationCompleted);
            }
            this.InvokeAsync("OnlineLogin", new object[] {
                        idterminal,
                        idUser,
                        login,
                        password,
                        hashPassword,
                        userID}, this.OnlineLoginOperationCompleted, userState);
        }
        
        private void OnOnlineLoginOperationCompleted(object arg) {
            if ((this.OnlineLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnlineLoginCompleted(this, new OnlineLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://LoginService.fask.cz/")]
    public partial class StatusObject {
        
        private string _statusFileField;
        
        private string statusTextField;
        
        private bool exceptionField;
        
        private System.DateTime datumZapisuField;
        
        private bool finishedField;
        
        public StatusObject() {
            this.finishedField = false;
        }
        
        /// <remarks/>
        public string _statusFile {
            get {
                return this._statusFileField;
            }
            set {
                this._statusFileField = value;
            }
        }
        
        /// <remarks/>
        public string StatusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        public bool Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatumZapisu {
            get {
                return this.datumZapisuField;
            }
            set {
                this.datumZapisuField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Finished {
            get {
                return this.finishedField;
            }
            set {
                this.finishedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetKatalogUzivateleTestCompletedEventHandler(object sender, GetKatalogUzivateleTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKatalogUzivateleTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKatalogUzivateleTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetKatalogUzivateleCompletedEventHandler(object sender, GetKatalogUzivateleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKatalogUzivateleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKatalogUzivateleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetKatalogUzivateleSPravamaCompletedEventHandler(object sender, GetKatalogUzivateleSPravamaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKatalogUzivateleSPravamaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKatalogUzivateleSPravamaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetHashCompletedEventHandler(object sender, GetHashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OnlineLoginCompletedEventHandler(object sender, OnlineLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnlineLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnlineLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int userID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591