//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASK.SledovaniVyroby.Module.MST_Prodej.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\SQLDBs\\TypDokladu.sdf")]
        public string TypDokladuConnectionString {
            get {
                return ((string)(this["TypDokladuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\_work_\\_Vyvoj_Subversion_01\\MST_06_alfa\\SERVER\\MST_Win_Kom_Server\\" +
            "SqlCEDBs\\TypDokladu.sdf")]
        public string TypDokladuConnectionString1 {
            get {
                return ((string)(this["TypDokladuConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\_work_\\_Vyvoj_Subversion_01\\MST_06_alfa\\SERVER\\MST_Win_Kom_Server\\" +
            "SqlCEDBs\\Prodej.sdf")]
        public string ProdejConnectionString {
            get {
                return ((string)(this["ProdejConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\_work_\\_Vyvoj_Subversion_01\\MST_06_alfa\\SERVER\\MST_Win_Kom_Server\\" +
            "SqlCEDBs\\Odberatele.sdf")]
        public string OdberateleConnectionString {
            get {
                return ((string)(this["OdberateleConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\_work_\\_Vyvoj_Subversion_01\\MST_06_alfa\\SERVER\\MST_Win_Kom_Server\\" +
            "SqlCEDBs\\Meny.sdf")]
        public string MenyConnectionString {
            get {
                return ((string)(this["MenyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\_work_\\_Vyvoj_Subversion_01\\MST_06_alfa\\SERVER\\MST_Win_Kom_Server\\" +
            "SqlCEDBs\\Sklady.sdf")]
        public string SkladyConnectionString {
            get {
                return ((string)(this["SkladyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/MST_Win_Kom_Server_6_alfa/Prodej.asmx")]
        public string MST_Prodej_ProdejService_ProdejService {
            get {
                return ((string)(this["MST_Prodej_ProdejService_ProdejService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/MST_Win_Kom_Server_6_alfa/Informations.asmx")]
        public string MST_Prodej_InformationService_InformationsService {
            get {
                return ((string)(this["MST_Prodej_InformationService_InformationsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/MST_Win_Kom_Server_6_alfa/Configuration.asmx")]
        public string MST_Prodej_ConfigurationService_Configuration {
            get {
                return ((string)(this["MST_Prodej_ConfigurationService_Configuration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/MST_Win_Kom_Server_6_alfa/Ciselnik.asmx")]
        public string MST_Prodej_CiselnikService_CiselnikService {
            get {
                return ((string)(this["MST_Prodej_CiselnikService_CiselnikService"]));
            }
        }
    }
}
