using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fask.Module.ABRA.SAB.Classes.ABRA_BO
{

    public class Rootobject_FV
    {
        //public DateTime accdatedate { get; set; }
        //public string accdocqueue_id { get; set; }
        //public int accountingtype { get; set; }
        //public string accpresetdef_id { get; set; }
        //public string address_id { get; set; }
        //public int amount { get; set; }
        //public float amountwithoutvat { get; set; }
        //public float amountwithoutvatwithvatdeposit { get; set; }
        //public int amountwithvatdeposit { get; set; }
        //public string bankaccount_id { get; set; }
        //public float capacity { get; set; }
        //public int capacityunit { get; set; }
        //public string classid { get; set; }
        //public object closingperiod_id { get; set; }
        //public int coef { get; set; }
        //public object constsymbol_id { get; set; }
        //public object correctedatdate { get; set; }
        //public object correctedby_id { get; set; }
        //public string country_id { get; set; }
        //public DateTime createdatdate { get; set; }
        //public string createdby_id { get; set; }
        //public int creditamount { get; set; }
        //public int creditamountwithoutvat { get; set; }
        //public string currency_id { get; set; }
        //public int currrate { get; set; }
        //public string currrateinfo { get; set; }
        //public object dealercategory_id { get; set; }
        //public int dealerdiscount { get; set; }
        //public int dealerdiscountkind { get; set; }
        //public int deliverymode { get; set; }
        //public string description { get; set; }
        //public bool dirty { get; set; }
        //public int discountcalckind { get; set; }
        public string displayname { get; set; }
        //public DateTime docdatedate { get; set; }
        //public string docqueue_id { get; set; }
        //public int documentdiscount { get; set; }
        //public string docuuid { get; set; }
        //public DateTime duedatedate { get; set; }
        //public int dueterm { get; set; }
        //public string externalnumber { get; set; }
        //public int financialdiscount { get; set; }
        //public string firm_id { get; set; }
        //public int firmcredit { get; set; }
        //public int firmcreditsurvival { get; set; }
        //public int firmnotpaidamount { get; set; }
        //public string firmoffice_id { get; set; }
        //public int firmofficecredit { get; set; }
        //public int firmofficecreditsurvival { get; set; }
        //public int firmofficenotpaidamount { get; set; }
        //public bool frozendiscounts { get; set; }
        public string id { get; set; }
        //public int intrastatcompletekind { get; set; }
        //public object intrastatdeliveryterm_id { get; set; }
        //public object intrastattransactiontype_id { get; set; }
        //public object intrastattransportationtype_id { get; set; }
        //public bool isaccounted { get; set; }
        //public bool isaccountedlatervat { get; set; }
        //public bool isfinancialdiscount { get; set; }
        //public bool isprofit { get; set; }
        //public bool isreversechargedeclared { get; set; }
        //public bool isrowdiscount { get; set; }
        //public object lastpaymentperiod_id { get; set; }
        //public int localamount { get; set; }
        //public float localamountwithoutvat { get; set; }
        //public float localamountwithoutvatwithvatdeposit { get; set; }
        //public int localamountwithvatdeposit { get; set; }
        //public int localcoef { get; set; }
        //public int localcreditamount { get; set; }
        //public int localcreditamountwithoutvat { get; set; }
        //public int localnotpaidamount { get; set; }
        //public int localpaidamount { get; set; }
        //public int localpaidcreditamount { get; set; }
        //public string localrefcurrency_id { get; set; }
        //public int localroundingamount { get; set; }
        //public float localvatamount { get; set; }
        //public object localzone_id { get; set; }
        //public float margin { get; set; }
        //public string masterdocclsid { get; set; }
        //public string masterdocument_id { get; set; }
        //public string newrelateddocument_id { get; set; }
        //public int newrelatedtype { get; set; }
        //public int notpaidamount { get; set; }
        //public int objversion { get; set; }
        //public int ordnumber { get; set; }
        //public int paidamount { get; set; }
        //public int paidcreditamount { get; set; }
        //public int paymentremindercount { get; set; }
        //public object paymenttype_id { get; set; }
        //public string payremdescription { get; set; }
        //public string payremenforcestate_id { get; set; }
        //public DateTime payremexcldatetodate { get; set; }
        //public string payremexclreason { get; set; }
        //public DateTime payremfirstsetdatedate { get; set; }
        //public bool payremhandedover { get; set; }
        //public string payremperson_id { get; set; }
        //public int penaltycount { get; set; }
        //public string period_id { get; set; }
        //public object person_id { get; set; }
        //public int priceprecision { get; set; }
        //public bool priceswithvat { get; set; }
        //public int quantitydiscountkind { get; set; }
        //public string receiptcarddocqueue_id { get; set; }
        //public string refcurrency_id { get; set; }
        //public int refcurrrate { get; set; }
        //public int roundingamount { get; set; }
        public Row_FV[] rows { get; set; }
        //public object[] scontodefinitions { get; set; }
        //public bool scontodefinitionsexists { get; set; }
        //public bool simplifiedvatdocument { get; set; }
        //public string storedocqueue_id { get; set; }
        //public int storeprice { get; set; }
        //public int totaldiscountamount { get; set; }
        //public int totalrounding { get; set; }
        //public int tradetype { get; set; }
        //public string tradetypedescription { get; set; }
        //public object transportationtype_id { get; set; }
        //public string varsymbol { get; set; }
        //public DateTime vatadmitdatedate { get; set; }
        //public int vatalgorithm { get; set; }
        //public float vatamount { get; set; }
        //public bool vatbypayment { get; set; }
        //public object vatbypaymentenddatedate { get; set; }
        //public string vatcountry_id { get; set; }
        //public DateTime vatdatedate { get; set; }
        //public bool vatdocument { get; set; }
        //public int vatfromaboveprecision { get; set; }
        //public int vatfromabovetype { get; set; }
        //public string vatreportpreference { get; set; }
        //public string vatreportreference { get; set; }
        //public int vatrounding { get; set; }
        //public bool vatvoluntarypaid { get; set; }
        //public int weight { get; set; }
        //public int weightunit { get; set; }
        //public object zone_id { get; set; }
    }

    public class Row_FV
    {
        //public object account_id { get; set; }
        //public object busorder_id { get; set; }
        //public object busproject_id { get; set; }
        //public object bustransaction_id { get; set; }
        //public float capacity { get; set; }
        //public int capacityunit { get; set; }
        //public string classid { get; set; }
        //public int dealerdiscount { get; set; }
        //public bool dealerdiscountexcluded { get; set; }
        //public int deliverymode { get; set; }
        //public string deliveryprovidemodestr { get; set; }
        //public bool discountsexcluded { get; set; }
        public string displayname { get; set; }
        //public string division_id { get; set; }
        //public bool documentdiscountexcluded { get; set; }
        //public object drcarticle_id { get; set; }
        //public int drcquantity { get; set; }
        //public string drcqunit { get; set; }
        //public object esldatedate { get; set; }
        //public object eslindicator_id { get; set; }
        //public int eslstatus { get; set; }
        //public bool financialdiscountexcluded { get; set; }
        public string id { get; set; }
        //public object incometype_id { get; set; }
        //public bool individualdiscountexcluded { get; set; }
        //public int intrastatamount { get; set; }
        //public object intrastatoutputstatistic_id { get; set; }
        //public object intrastatregion_id { get; set; }
        //public int intrastatstatus { get; set; }
        //public bool isanydiscount { get; set; }
        //public int localintrastatamount { get; set; }
        //public int localtamount { get; set; }
        //public float localtamountwithoutvat { get; set; }
        //public object mossservice_id { get; set; }
        //public int objversion { get; set; }
        public string parent_id { get; set; }
        //public int posindex { get; set; }
        //public string provide_id { get; set; }
        //public string providerow_id { get; set; }
        //public string providerowdisplayname { get; set; }
        public float quantity { get; set; }
        //public int quantitydiscount { get; set; }
        //public bool quantitydiscountexcluded { get; set; }
        //public string qunit { get; set; }
        //public int rowdiscount { get; set; }
        //public int rowmargin { get; set; }
        //public int rowstoreprice { get; set; }
        //public int rowtype { get; set; }
        //public string sibblingid { get; set; }
        //public object sourcegroupidentical_id { get; set; }
        //public bool splitintrastat { get; set; }
        //public int statisticamount { get; set; }
        public string store_id { get; set; }
        public string storecard_id { get; set; }
        //public int tamount { get; set; }
        //public float tamountwithoutvat { get; set; }
        //public string text { get; set; }
        //public bool toesl { get; set; }
        //public bool tointrastat { get; set; }
        //public int totaldiscountfactor { get; set; }
        //public int totalpercentualdiscount { get; set; }
        //public float totalprice { get; set; }
        //public float unitprice { get; set; }
        //public int unitquantity { get; set; }
        //public int unitrate { get; set; }
        //public string vatdeposit_id { get; set; }
        //public string vatdepositrow_id { get; set; }
        //public string vatindex_id { get; set; }
        //public int vatmode { get; set; }
        //public int vatrate { get; set; }
        //public string vatrate_id { get; set; }
        //public float weight { get; set; }
        //public int weightunit { get; set; }
    }

}
