//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9151.
// 
namespace Fask.MST_W.ConfigurationService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfigurationSoap", Namespace="http://Configuration.fask.cz/")]
    public partial class Configuration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Configuration() {
            this.Url = "http://localhost/MST_Win_Kom_Server_7_Cipisek/Configuration.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Configuration.fask.cz/GetPasswords", RequestNamespace="http://Configuration.fask.cz/", ResponseNamespace="http://Configuration.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPasswords() {
            object[] results = this.Invoke("GetPasswords", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPasswords(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPasswords", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPasswords(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Configuration.fask.cz/GetTypyPalet", RequestNamespace="http://Configuration.fask.cz/", ResponseNamespace="http://Configuration.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTypyPalet(byte idterminal) {
            object[] results = this.Invoke("GetTypyPalet", new object[] {
                        idterminal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTypyPalet(byte idterminal, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTypyPalet", new object[] {
                        idterminal}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetTypyPalet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Configuration.fask.cz/GetScannerConfig", RequestNamespace="http://Configuration.fask.cz/", ResponseNamespace="http://Configuration.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetScannerConfig() {
            object[] results = this.Invoke("GetScannerConfig", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetScannerConfig(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetScannerConfig", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetScannerConfig(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Configuration.fask.cz/SetScannerConfig", RequestNamespace="http://Configuration.fask.cz/", ResponseNamespace="http://Configuration.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetScannerConfig(string scannerconfig) {
            object[] results = this.Invoke("SetScannerConfig", new object[] {
                        scannerconfig});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetScannerConfig(string scannerconfig, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetScannerConfig", new object[] {
                        scannerconfig}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSetScannerConfig(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Configuration.fask.cz/GetModulesConfig", RequestNamespace="http://Configuration.fask.cz/", ResponseNamespace="http://Configuration.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetModulesConfig() {
            object[] results = this.Invoke("GetModulesConfig", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetModulesConfig(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetModulesConfig", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetModulesConfig(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Configuration.fask.cz/GetLicenceInfo", RequestNamespace="http://Configuration.fask.cz/", ResponseNamespace="http://Configuration.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public License GetLicenceInfo() {
            object[] results = this.Invoke("GetLicenceInfo", new object[0]);
            return ((License)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLicenceInfo(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLicenceInfo", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public License EndGetLicenceInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((License)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Configuration.fask.cz/GetCZMSTCFG", RequestNamespace="http://Configuration.fask.cz/", ResponseNamespace="http://Configuration.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public dsCZMSTCFG GetCZMSTCFG() {
            object[] results = this.Invoke("GetCZMSTCFG", new object[0]);
            return ((dsCZMSTCFG)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCZMSTCFG(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCZMSTCFG", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public dsCZMSTCFG EndGetCZMSTCFG(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dsCZMSTCFG)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Configuration.fask.cz/")]
    public partial class License {
        
        /// <remarks/>
        public string numberTerminal;
        
        /// <remarks/>
        public string company;
        
        /// <remarks/>
        public string contact;
        
        /// <remarks/>
        public string expiration;
        
        /// <remarks/>
        public string encryprition;
        
        /// <remarks/>
        public string created;
        
        /// <remarks/>
        public bool isValid;
        
        /// <remarks/>
        public bool isExpirated;
        
        /// <remarks/>
        public bool showInfoExpirationInTerminal;
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // This type definition was generated by System.Data.Design.TypedDataSetSchemaImporterExtension schema importer extension.
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsCZMSTCFG")]
    public partial class dsCZMSTCFG : global::System.Data.DataSet {
        
        private CZMSTCFGDataTable tableCZMSTCFG;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsCZMSTCFG() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CZMSTCFGDataTable CZMSTCFG {
            get {
                return this.tableCZMSTCFG;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsCZMSTCFG cln = ((dsCZMSTCFG)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["CZMSTCFG"] != null)) {
                    base.Tables.Add(new CZMSTCFGDataTable(ds.Tables["CZMSTCFG"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableCZMSTCFG = ((CZMSTCFGDataTable)(base.Tables["CZMSTCFG"]));
            if ((initTable == true)) {
                if ((this.tableCZMSTCFG != null)) {
                    this.tableCZMSTCFG.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsCZMSTCFG";
            this.Prefix = "";
            this.Namespace = "http://fask.cz/dsCZMSTCFG.xsd";
            this.Locale = new global::System.Globalization.CultureInfo("");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableCZMSTCFG = new CZMSTCFGDataTable();
            base.Tables.Add(this.tableCZMSTCFG);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeCZMSTCFG() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsCZMSTCFG ds = new dsCZMSTCFG();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void CZMSTCFGRowChangeEventHandler(object sender, CZMSTCFGRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CZMSTCFGDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnPNAME;
            
            private global::System.Data.DataColumn columnPVALUEBL;
            
            private global::System.Data.DataColumn columnPVALUEIN;
            
            private global::System.Data.DataColumn columnPVALUECH;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CZMSTCFGDataTable() {
                this.TableName = "CZMSTCFG";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CZMSTCFGDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PNAMEColumn {
                get {
                    return this.columnPNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PVALUEBLColumn {
                get {
                    return this.columnPVALUEBL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PVALUEINColumn {
                get {
                    return this.columnPVALUEIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PVALUECHColumn {
                get {
                    return this.columnPVALUECH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CZMSTCFGRow this[int index] {
                get {
                    return ((CZMSTCFGRow)(this.Rows[index]));
                }
            }
            
            public event CZMSTCFGRowChangeEventHandler CZMSTCFGRowChanging;
            
            public event CZMSTCFGRowChangeEventHandler CZMSTCFGRowChanged;
            
            public event CZMSTCFGRowChangeEventHandler CZMSTCFGRowDeleting;
            
            public event CZMSTCFGRowChangeEventHandler CZMSTCFGRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddCZMSTCFGRow(CZMSTCFGRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CZMSTCFGRow AddCZMSTCFGRow(string PNAME, byte PVALUEBL, int PVALUEIN, string PVALUECH) {
                CZMSTCFGRow rowCZMSTCFGRow = ((CZMSTCFGRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        PNAME,
                        PVALUEBL,
                        PVALUEIN,
                        PVALUECH};
                rowCZMSTCFGRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowCZMSTCFGRow);
                return rowCZMSTCFGRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                CZMSTCFGDataTable cln = ((CZMSTCFGDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new CZMSTCFGDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnPNAME = base.Columns["PNAME"];
                this.columnPVALUEBL = base.Columns["PVALUEBL"];
                this.columnPVALUEIN = base.Columns["PVALUEIN"];
                this.columnPVALUECH = base.Columns["PVALUECH"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnPNAME = new global::System.Data.DataColumn("PNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPNAME);
                this.columnPVALUEBL = new global::System.Data.DataColumn("PVALUEBL", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPVALUEBL);
                this.columnPVALUEIN = new global::System.Data.DataColumn("PVALUEIN", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPVALUEIN);
                this.columnPVALUECH = new global::System.Data.DataColumn("PVALUECH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPVALUECH);
                this.columnPNAME.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CZMSTCFGRow NewCZMSTCFGRow() {
                return ((CZMSTCFGRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new CZMSTCFGRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(CZMSTCFGRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CZMSTCFGRowChanged != null)) {
                    this.CZMSTCFGRowChanged(this, new CZMSTCFGRowChangeEvent(((CZMSTCFGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CZMSTCFGRowChanging != null)) {
                    this.CZMSTCFGRowChanging(this, new CZMSTCFGRowChangeEvent(((CZMSTCFGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CZMSTCFGRowDeleted != null)) {
                    this.CZMSTCFGRowDeleted(this, new CZMSTCFGRowChangeEvent(((CZMSTCFGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CZMSTCFGRowDeleting != null)) {
                    this.CZMSTCFGRowDeleting(this, new CZMSTCFGRowChangeEvent(((CZMSTCFGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveCZMSTCFGRow(CZMSTCFGRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsCZMSTCFG ds = new dsCZMSTCFG();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CZMSTCFGDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class CZMSTCFGRow : global::System.Data.DataRow {
            
            private CZMSTCFGDataTable tableCZMSTCFG;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CZMSTCFGRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCZMSTCFG = ((CZMSTCFGDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PNAME {
                get {
                    return ((string)(this[this.tableCZMSTCFG.PNAMEColumn]));
                }
                set {
                    this[this.tableCZMSTCFG.PNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte PVALUEBL {
                get {
                    try {
                        return ((byte)(this[this.tableCZMSTCFG.PVALUEBLColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PVALUEBL\' in table \'CZMSTCFG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCZMSTCFG.PVALUEBLColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int PVALUEIN {
                get {
                    try {
                        return ((int)(this[this.tableCZMSTCFG.PVALUEINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PVALUEIN\' in table \'CZMSTCFG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCZMSTCFG.PVALUEINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PVALUECH {
                get {
                    try {
                        return ((string)(this[this.tableCZMSTCFG.PVALUECHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PVALUECH\' in table \'CZMSTCFG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCZMSTCFG.PVALUECHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPVALUEBLNull() {
                return this.IsNull(this.tableCZMSTCFG.PVALUEBLColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPVALUEBLNull() {
                this[this.tableCZMSTCFG.PVALUEBLColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPVALUEINNull() {
                return this.IsNull(this.tableCZMSTCFG.PVALUEINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPVALUEINNull() {
                this[this.tableCZMSTCFG.PVALUEINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPVALUECHNull() {
                return this.IsNull(this.tableCZMSTCFG.PVALUECHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPVALUECHNull() {
                this[this.tableCZMSTCFG.PVALUECHColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        public class CZMSTCFGRowChangeEvent : global::System.EventArgs {
            
            private CZMSTCFGRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CZMSTCFGRowChangeEvent(CZMSTCFGRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CZMSTCFGRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
