/****** Object:  Table [dbo].[FASK_ZASOBY_PARAMETRY]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FASK_ZASOBY_PARAMETRY](
	[DEX_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEMNMBR] [nvarchar](40) NOT NULL,
	[VPrFVTS] [bit] NOT NULL,
	[VPrFPTS] [bit] NOT NULL,
	[VPrFDTS] [bit] NOT NULL,
	[VPrFITS] [bit] NOT NULL,
	[VPrFXTS] [bit] NOT NULL,
	[RefVPrFVTS] [int] NULL,
	[RefVPrFPTS] [int] NULL,
	[RefVPrFDTS] [int] NULL,
	[RefVPrFITS] [int] NULL,
	[RefVPrFXTS] [int] NULL,
	[VPrTIMEPREP] [float] NULL,
	[VPrTIMEUNIT] [float] NULL,
	[RefVPrTIMEMODE] [int] NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[FASK_ZASOBY_PARAMETRY] ADD  CONSTRAINT [DF_FASK_ZASOBY_PARAMETRY_VPrFVTS]  DEFAULT ((0)) FOR [VPrFVTS]
GO
ALTER TABLE [dbo].[FASK_ZASOBY_PARAMETRY] ADD  CONSTRAINT [DF_FASK_ZASOBY_PARAMETRY_VPrFPTS]  DEFAULT ((0)) FOR [VPrFPTS]
GO
ALTER TABLE [dbo].[FASK_ZASOBY_PARAMETRY] ADD  CONSTRAINT [DF_FASK_ZASOBY_PARAMETRY_VPrFDTS]  DEFAULT ((0)) FOR [VPrFDTS]
GO
ALTER TABLE [dbo].[FASK_ZASOBY_PARAMETRY] ADD  CONSTRAINT [DF_FASK_ZASOBY_PARAMETRY_VPrFITS]  DEFAULT ((0)) FOR [VPrFITS]
GO
ALTER TABLE [dbo].[FASK_ZASOBY_PARAMETRY] ADD  CONSTRAINT [DF_FASK_ZASOBY_PARAMETRY_VPrFXTS]  DEFAULT ((0)) FOR [VPrFXTS]
GO
/**************************************************************************************/