--Překopirovaní puvodnych typu dokladu do novych
--POZOR na constrain
--přemenovat staru na CZMST092_OLD

INSERT INTO [dbo].[CZMST092]
           (
		   [doc_id]
           ,[doc_id2]
           ,[doc_desc]
           ,[doc_typ]
           ,[doc_carcode]

           ,[LOCNCODE]
           ,[cfg_odb]
           ,[cfg_str]
           ,[cfg_prac]
           ,[cfg_mn2sn]

           ,[cfg_disp]
           ,[cfg_disp_dest]
           ,[cfg_palety]
           ,[cfg_paleta_id]
           ,[cfg_zakazka_id]

           ,[cfg_mena_id]
           ,[cfg_tisk]
           ,[cfg_prevod_sklad]
           ,[cfg_tisk_soupis]
           ,[SKL_ID]

           ,[cfg_lokace]
           ,[cfg_lokace_ciselnik]
           ,[cfg_lokace_dest]
           ,[cfg_onl_dop_pal]
           ,[cfg_onl_over_lokace]

           ,[cfg_onl_over_lokace_dest]
           ,[cfg_mnozstvi_ze_zbozi]
           ,[cfg_predvyplnit_mnozstvi]
           ,[cfg_skl_id_dest]
           ,[predvyplnit_skl_id_dest]

           ,[cfg_lok_mech]
           ,[cfg_lok_mech_pohyb_type]
           ,[cfg_skl_id_dest_prevzit]
           ,[cfg_lokace_dest_ciselnik]
           ,[predvyplnit_locncodedest]

           ,[cfg_sklady]
           ,[cfg_onl_dop_lokace_dest]
           ,[cfg_generovat_sn]
           ,[cfg_parsovat_ck]
           ,[cfg_sn_na_davku]

           ,[cfg_lok_mech_online_pohyby]
           ,[cfg_onl_palety_generovat]
           ,[cfg_tisk_palety]
           ,[cfg_sklady_zmena]
           ,[cfg_delka_SN]

           ,[cfg_Navrh]
           ,[cfg_FIFO_FEFO_check]
		   )
		   (SELECT 
		   [doc_id]
			,[doc_id2]
			,[doc_desc]
			,[doc_typ]
			,[doc_carcode]
			,[LOCNCODE]
			,[cfg_odb]
			,[cfg_str]
			,[cfg_prac]
			,[cfg_mn2sn]
			,[cfg_disp]
			, 0 as [cfg_disp_dest]
			,[cfg_palety]
			,[cfg_paleta_id]
			,[cfg_zakazka_id]
			,[cfg_mena_id]
			,[cfg_tisk]
			,[cfg_prevod_sklad]
			,[cfg_tisk_soupis]
			,[SKL_ID]
			,[cfg_lokace]
			,[cfg_lokace_ciselnik]
			,[cfg_lokace_dest]
			,[cfg_onl_dop_pal]
			,[cfg_onl_over_lokace]
			,[cfg_onl_over_lokace_dest]
			,[cfg_mnozstvi_ze_zbozi]
			,[cfg_predvyplnit_mnozstvi]
			,[cfg_skl_id_dest]
			,[predvyplnit_skl_id_dest]
			,[cfg_lok_mech]
			,[cfg_lok_mech_pohyb_type]
			,[cfg_skl_id_dest_prevzit]
			,[cfg_lokace_dest_ciselnik]
			,[predvyplnit_locncodedest]
			,[cfg_sklady]
			,[cfg_onl_dop_lokace_dest]
			,[cfg_generovat_sn]
			,[cfg_parsovat_ck]
			,[cfg_sn_na_davku]
			,[cfg_lok_mech_online_pohyby]
			,[cfg_onl_palety_generovat]
			,[cfg_tisk_palety]
			,[cfg_sklady_zmena]
			,[cfg_delka_SN]
			,[cfg_Navrh]
			,[cfg_FIFO_FEFO_check]
		FROM [dbo].[CZMST092_OLD])