

DECLARE @ITEMNMBR int;
DECLARE @SKL_ID int;
DECLARE @QTYSHPPD numeric(19,5)
DECLARE @SERLTNUM nvarchar(50)
DECLARE @LOCNCODE nvarchar(11)


DECLARE @TabulkaMena TABLE
(
ITEMNMBR int,
SKL_ID int,
LOCNCODE nvarchar(11),
ITEMDESC nvarchar(100)
)



DECLARE curPol CURSOR FOR
SELECT 
ITEMNMBR, 
SKL_ID,
QTYSHPPD,
SERLTNUM,
LOCNCODE
FROM
CZMST_SkladLokace_Stav
where ITEMDESC = ''

OPEN curPol
WHILE (1=1) 
	BEGIN
	
	FETCH NEXT FROM curPol INTO @ITEMNMBR, @SKL_ID, @QTYSHPPD, @SERLTNUM, @LOCNCODE
	IF @@FETCH_STATUS <> 0
	BEGIN
		BREAK
	END

	DECLARE @ITEMDESC_map nvarchar(200)

	SELECT @ITEMDESC_map = ITEMDESC FROM FASK_ZASOBY WHERE ITEMNMBR = @ITEMNMBR AND SKL_ID = @SKL_ID

						insert into @TabulkaMena(ITEMNMBR, SKL_ID, LOCNCODE, ITEMDESC) values (@ITEMNMBR, @SKL_ID, @LOCNCODE, @ITEMDESC_map)

		--UPDATE [dbo].[CZMST_SkladLokace_Stav]
		--SET [ITEMDESC] = @ITEMDESC_map
		--WHERE 
		--ITEMNMBR = @ITEMNMBR AND SERLTNUM = @SERLTNUM AND SKL_ID = @SKL_ID AND LOCNCODE = @LOCNCODE AND QTYSHPPD = @QTYSHPPD


	END
CLOSE curPol
DEALLOCATE curPol


SELECT * FROM @TabulkaMena