select 
O.TABLE_NAME, 
O.COLUMN_DEFAULT, 
O.IS_NULLABLE, 
O.DATA_TYPE, 
O.CHARACTER_MAXIMUM_LENGTH, 
O.NUMERIC_PRECISION, 
O.NUMERIC_SCALE, 
O.DATETIME_PRECISION, 
O.COLUMN_NAME,

C.TABLE_NAME, 
C.COLUMN_DEFAULT, 
C.IS_NULLABLE, 
C.DATA_TYPE, 
C.CHARACTER_MAXIMUM_LENGTH, 
C.NUMERIC_PRECISION, 
C.NUMERIC_SCALE, 
C.DATETIME_PRECISION, 
C.COLUMN_NAME
from FASKPOH_HANIBAL_TEST_Cip.INFORMATION_SCHEMA.COLUMNS as O
left join FASK__update.INFORMATION_SCHEMA.COLUMNS as C 
ON C.TABLE_NAME = O.TABLE_NAME AND C.COLUMN_NAME = O.COLUMN_NAME
WHERE
O.COLUMN_DEFAULT != C.COLUMN_DEFAULT OR
O.IS_NULLABLE != C.IS_NULLABLE OR 
O.DATA_TYPE != O.DATA_TYPE OR
O.CHARACTER_MAXIMUM_LENGTH != C.CHARACTER_MAXIMUM_LENGTH OR
O.NUMERIC_PRECISION != C.NUMERIC_PRECISION OR 
O.NUMERIC_SCALE != C.NUMERIC_SCALE OR
O.DATETIME_PRECISION != C.DATETIME_PRECISION 
