create table [CZMST092]
(
    [doc_id] TEXT not null,
    [doc_desc] TEXT,
    [doc_typ] TEXT,
    [doc_carcode] TEXT,
    [DEX_ROW_ID] INTEGER not null,
    [LOCNCODE] TEXT not null,
    [cfg_odb] INTEGER not null,
    [cfg_str] INTEGER not null,
    [cfg_disp] INTEGER not null,
    [cfg_disp_dest] INTEGER not null,
    [cfg_mn2sn] INTEGER not null,
    [cfg_prac] INTEGER not null default 0,
    [cfg_palety] INTEGER not null default 0,
    [cfg_paleta_id] INTEGER not null,
    [cfg_zakazka_id] INTEGER not null,
    [cfg_mena_id] INTEGER,
    [doc_id2] TEXT not null default '',
    [cfg_tisk] INTEGER not null,
    [cfg_prevod_sklad] INTEGER not null,
    [cfg_tisk_soupis] INTEGER,
    [SKL_ID] TEXT,
    [cfg_lokace] INTEGER,
    [cfg_lokace_ciselnik] INTEGER,
    [cfg_lokace_dest] INTEGER,
    [cfg_onl_dop_pal] INTEGER,
    [cfg_onl_over_lokace] INTEGER,
    [cfg_onl_over_lokace_dest] INTEGER,
    [cfg_mnozstvi_ze_zbozi] INTEGER,
    [cfg_predvyplnit_mnozstvi] INTEGER,
    [cfg_skl_id_dest] INTEGER,
    [predvyplnit_skl_id_dest] TEXT,
    [cfg_lok_mech] INTEGER,
    [cfg_lok_mech_pohyb_type] TEXT,
    [cfg_skl_id_dest_prevzit] INTEGER,
    [cfg_lokace_dest_ciselnik] INTEGER,
    [predvyplnit_locncodedest] TEXT,
    [cfg_sklady] INTEGER,
    [cfg_onl_dop_lokace_dest] INTEGER,
    [cfg_generovat_sn] INTEGER,
    [cfg_parsovat_ck] INTEGER,
    [cfg_sn_na_davku] INTEGER,
    [cfg_lok_mech_online_pohyby] INTEGER,
    [cfg_onl_palety_generovat] INTEGER,
    [cfg_tisk_palety] INTEGER,
    [cfg_sklady_zmena] INTEGER,
    [cfg_delka_SN] INTEGER,
    [cfg_Navrh] INTEGER,
    [cfg_sarze_ONOFF] INTEGER default 1,
    [cfg_sn_ONOFF] INTEGER default 1,
    [cfg_expirace_ONOFF] INTEGER default 1,
    [cfg_AttributeToSN_ONOFF] INTEGER default 0
);

