//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9151.
// 
namespace Fask.PrinterProviderWebService.PrintServerTestService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TestSoap", Namespace="http://Test.fask.cz/")]
    public partial class Test : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Test() {
            this.Url = "http://localhost/MST_Win_Kom_Server_7_Cipisek/Test.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/HelloWorld", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/WriteTo_Log_Server_Info_File", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteTo_Log_Server_Info_File(string Text) {
            object[] results = this.Invoke("WriteTo_Log_Server_Info_File", new object[] {
                        Text});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWriteTo_Log_Server_Info_File(string Text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WriteTo_Log_Server_Info_File", new object[] {
                        Text}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndWriteTo_Log_Server_Info_File(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/WriteTo_Trace_Server_Info_File", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteTo_Trace_Server_Info_File(string Text) {
            object[] results = this.Invoke("WriteTo_Trace_Server_Info_File", new object[] {
                        Text});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWriteTo_Trace_Server_Info_File(string Text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WriteTo_Trace_Server_Info_File", new object[] {
                        Text}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndWriteTo_Trace_Server_Info_File(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/WindowsIdentity", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WindowsIdentity() {
            object[] results = this.Invoke("WindowsIdentity", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWindowsIdentity(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WindowsIdentity", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndWindowsIdentity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/TestMail", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TestMail(string data) {
            object[] results = this.Invoke("TestMail", new object[] {
                        data});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTestMail(string data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestMail", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndTestMail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/Encodings", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Encodings() {
            object[] results = this.Invoke("Encodings", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEncodings(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Encodings", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEncodings(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/StatusObjectReturn", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject StatusObjectReturn(string fullpath) {
            object[] results = this.Invoke("StatusObjectReturn", new object[] {
                        fullpath});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStatusObjectReturn(string fullpath, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StatusObjectReturn", new object[] {
                        fullpath}, callback, asyncState);
        }
        
        /// <remarks/>
        public StatusObject EndStatusObjectReturn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/Labels", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Labels() {
            object[] results = this.Invoke("Labels", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLabels(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Labels", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndLabels(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/Test_Get_Rada", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test_Get_Rada(string Modul, string SKL_ID) {
            object[] results = this.Invoke("Test_Get_Rada", new object[] {
                        Modul,
                        SKL_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTest_Get_Rada(string Modul, string SKL_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Test_Get_Rada", new object[] {
                        Modul,
                        SKL_ID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTest_Get_Rada(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/CreateSQLiteFile", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateSQLiteFile() {
            object[] results = this.Invoke("CreateSQLiteFile", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateSQLiteFile(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateSQLiteFile", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCreateSQLiteFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Test.fask.cz/Test_Provider_Komunikace", RequestNamespace="http://Test.fask.cz/", ResponseNamespace="http://Test.fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test_Provider_Komunikace() {
            object[] results = this.Invoke("Test_Provider_Komunikace", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTest_Provider_Komunikace(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Test_Provider_Komunikace", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTest_Provider_Komunikace(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Test.fask.cz/")]
    public partial class StatusObject {
        
        private string _statusFileField;
        
        private string statusTextField;
        
        private bool exceptionField;
        
        private System.DateTime datumZapisuField;
        
        private bool finishedField;
        
        public StatusObject() {
            this.finishedField = false;
        }
        
        /// <remarks/>
        public string _statusFile {
            get {
                return this._statusFileField;
            }
            set {
                this._statusFileField = value;
            }
        }
        
        /// <remarks/>
        public string StatusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        public bool Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatumZapisu {
            get {
                return this.datumZapisuField;
            }
            set {
                this.datumZapisuField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Finished {
            get {
                return this.finishedField;
            }
            set {
                this.finishedField = value;
            }
        }
    }
}
