^XA
^XFR:ROW.ZPL
^PN0
^FN1^FD$ITEMNMBR$^FS
^FN2^FD$ITEMDESC$^FS
^FN3^FD$QTYSHPPD$^FS
^FN4^FD$MJ$^FS
^FN6^FD$VNDITNUM$^FS
^FN7^FD$CZ_CarKod$^FS
^XZ

^XA
^DFR:SN.ZPL
^POI
^XB
^CI31
^LL$LLSN$
^FO25,0^A0N,$FontSizeSN_HEIGHT$,$FontSizeSN_WIDTH$^FDVýr.č.:^FS
^FO125,0^A0N,$FontSizeSN_HEIGHT$,$FontSizeSN_WIDTH$^TBN,550,$LLSN$^FN1^FS
^XZ

^XA
^XFR:SN.ZPL
^PN0
^FN1^FD$SERLTNUMSeznam$^FS
^XZ