//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FASK.SledovaniVyroby.Module.ZZS.CiselnikService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CiselnikServiceSoap", Namespace="http://fask.cz/")]
    public partial class CiselnikService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback KatalogZboziExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogOdberateleExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogStrediskaExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogPracovniciExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogMenyExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogZboziDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogMenyDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogOdberateleDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogStrediskaDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogPracovniciDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogTypDokladuDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogSkladyExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogSkladyDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogLokaceDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogEventTypesDBPrepareOperationCompleted;
        
        private System.Threading.SendOrPostCallback KatalogTiskarnyDBPrepareOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CiselnikService() {
            this.Url = global::FASK.SledovaniVyroby.Module.ZZS.Properties.Settings.Default.ZZS_CiselnikService_CiselnikService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event KatalogZboziExportCompletedEventHandler KatalogZboziExportCompleted;
        
        /// <remarks/>
        public event KatalogOdberateleExportCompletedEventHandler KatalogOdberateleExportCompleted;
        
        /// <remarks/>
        public event KatalogStrediskaExportCompletedEventHandler KatalogStrediskaExportCompleted;
        
        /// <remarks/>
        public event KatalogPracovniciExportCompletedEventHandler KatalogPracovniciExportCompleted;
        
        /// <remarks/>
        public event KatalogMenyExportCompletedEventHandler KatalogMenyExportCompleted;
        
        /// <remarks/>
        public event KatalogZboziDBPrepareCompletedEventHandler KatalogZboziDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogMenyDBPrepareCompletedEventHandler KatalogMenyDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogOdberateleDBPrepareCompletedEventHandler KatalogOdberateleDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogStrediskaDBPrepareCompletedEventHandler KatalogStrediskaDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogPracovniciDBPrepareCompletedEventHandler KatalogPracovniciDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogTypDokladuDBPrepareCompletedEventHandler KatalogTypDokladuDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogSkladyExportCompletedEventHandler KatalogSkladyExportCompleted;
        
        /// <remarks/>
        public event KatalogSkladyDBPrepareCompletedEventHandler KatalogSkladyDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogLokaceDBPrepareCompletedEventHandler KatalogLokaceDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogEventTypesDBPrepareCompletedEventHandler KatalogEventTypesDBPrepareCompleted;
        
        /// <remarks/>
        public event KatalogTiskarnyDBPrepareCompletedEventHandler KatalogTiskarnyDBPrepareCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogZboziExport", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject KatalogZboziExport(byte idterminal, string prefixskladu) {
            object[] results = this.Invoke("KatalogZboziExport", new object[] {
                        idterminal,
                        prefixskladu});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogZboziExportAsync(byte idterminal, string prefixskladu) {
            this.KatalogZboziExportAsync(idterminal, prefixskladu, null);
        }
        
        /// <remarks/>
        public void KatalogZboziExportAsync(byte idterminal, string prefixskladu, object userState) {
            if ((this.KatalogZboziExportOperationCompleted == null)) {
                this.KatalogZboziExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogZboziExportOperationCompleted);
            }
            this.InvokeAsync("KatalogZboziExport", new object[] {
                        idterminal,
                        prefixskladu}, this.KatalogZboziExportOperationCompleted, userState);
        }
        
        private void OnKatalogZboziExportOperationCompleted(object arg) {
            if ((this.KatalogZboziExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogZboziExportCompleted(this, new KatalogZboziExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogOdberateleExport", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject KatalogOdberateleExport(byte idterminal) {
            object[] results = this.Invoke("KatalogOdberateleExport", new object[] {
                        idterminal});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogOdberateleExportAsync(byte idterminal) {
            this.KatalogOdberateleExportAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogOdberateleExportAsync(byte idterminal, object userState) {
            if ((this.KatalogOdberateleExportOperationCompleted == null)) {
                this.KatalogOdberateleExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogOdberateleExportOperationCompleted);
            }
            this.InvokeAsync("KatalogOdberateleExport", new object[] {
                        idterminal}, this.KatalogOdberateleExportOperationCompleted, userState);
        }
        
        private void OnKatalogOdberateleExportOperationCompleted(object arg) {
            if ((this.KatalogOdberateleExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogOdberateleExportCompleted(this, new KatalogOdberateleExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogStrediskaExport", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject KatalogStrediskaExport(byte idterminal) {
            object[] results = this.Invoke("KatalogStrediskaExport", new object[] {
                        idterminal});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogStrediskaExportAsync(byte idterminal) {
            this.KatalogStrediskaExportAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogStrediskaExportAsync(byte idterminal, object userState) {
            if ((this.KatalogStrediskaExportOperationCompleted == null)) {
                this.KatalogStrediskaExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogStrediskaExportOperationCompleted);
            }
            this.InvokeAsync("KatalogStrediskaExport", new object[] {
                        idterminal}, this.KatalogStrediskaExportOperationCompleted, userState);
        }
        
        private void OnKatalogStrediskaExportOperationCompleted(object arg) {
            if ((this.KatalogStrediskaExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogStrediskaExportCompleted(this, new KatalogStrediskaExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogPracovniciExport", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject KatalogPracovniciExport(byte idterminal) {
            object[] results = this.Invoke("KatalogPracovniciExport", new object[] {
                        idterminal});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogPracovniciExportAsync(byte idterminal) {
            this.KatalogPracovniciExportAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogPracovniciExportAsync(byte idterminal, object userState) {
            if ((this.KatalogPracovniciExportOperationCompleted == null)) {
                this.KatalogPracovniciExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogPracovniciExportOperationCompleted);
            }
            this.InvokeAsync("KatalogPracovniciExport", new object[] {
                        idterminal}, this.KatalogPracovniciExportOperationCompleted, userState);
        }
        
        private void OnKatalogPracovniciExportOperationCompleted(object arg) {
            if ((this.KatalogPracovniciExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogPracovniciExportCompleted(this, new KatalogPracovniciExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogMenyExport", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject KatalogMenyExport(byte idterminal) {
            object[] results = this.Invoke("KatalogMenyExport", new object[] {
                        idterminal});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogMenyExportAsync(byte idterminal) {
            this.KatalogMenyExportAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogMenyExportAsync(byte idterminal, object userState) {
            if ((this.KatalogMenyExportOperationCompleted == null)) {
                this.KatalogMenyExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogMenyExportOperationCompleted);
            }
            this.InvokeAsync("KatalogMenyExport", new object[] {
                        idterminal}, this.KatalogMenyExportOperationCompleted, userState);
        }
        
        private void OnKatalogMenyExportOperationCompleted(object arg) {
            if ((this.KatalogMenyExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogMenyExportCompleted(this, new KatalogMenyExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogZboziDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject KatalogZboziDBPrepare(byte idterminal, string prefixskladu) {
            object[] results = this.Invoke("KatalogZboziDBPrepare", new object[] {
                        idterminal,
                        prefixskladu});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogZboziDBPrepareAsync(byte idterminal, string prefixskladu) {
            this.KatalogZboziDBPrepareAsync(idterminal, prefixskladu, null);
        }
        
        /// <remarks/>
        public void KatalogZboziDBPrepareAsync(byte idterminal, string prefixskladu, object userState) {
            if ((this.KatalogZboziDBPrepareOperationCompleted == null)) {
                this.KatalogZboziDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogZboziDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogZboziDBPrepare", new object[] {
                        idterminal,
                        prefixskladu}, this.KatalogZboziDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogZboziDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogZboziDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogZboziDBPrepareCompleted(this, new KatalogZboziDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogMenyDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogMenyDBPrepare(byte idterminal) {
            object[] results = this.Invoke("KatalogMenyDBPrepare", new object[] {
                        idterminal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogMenyDBPrepareAsync(byte idterminal) {
            this.KatalogMenyDBPrepareAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogMenyDBPrepareAsync(byte idterminal, object userState) {
            if ((this.KatalogMenyDBPrepareOperationCompleted == null)) {
                this.KatalogMenyDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogMenyDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogMenyDBPrepare", new object[] {
                        idterminal}, this.KatalogMenyDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogMenyDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogMenyDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogMenyDBPrepareCompleted(this, new KatalogMenyDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogOdberateleDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogOdberateleDBPrepare(byte idterminal, string prefixskladu) {
            object[] results = this.Invoke("KatalogOdberateleDBPrepare", new object[] {
                        idterminal,
                        prefixskladu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogOdberateleDBPrepareAsync(byte idterminal, string prefixskladu) {
            this.KatalogOdberateleDBPrepareAsync(idterminal, prefixskladu, null);
        }
        
        /// <remarks/>
        public void KatalogOdberateleDBPrepareAsync(byte idterminal, string prefixskladu, object userState) {
            if ((this.KatalogOdberateleDBPrepareOperationCompleted == null)) {
                this.KatalogOdberateleDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogOdberateleDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogOdberateleDBPrepare", new object[] {
                        idterminal,
                        prefixskladu}, this.KatalogOdberateleDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogOdberateleDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogOdberateleDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogOdberateleDBPrepareCompleted(this, new KatalogOdberateleDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogStrediskaDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogStrediskaDBPrepare(byte idterminal, string prefixskladu) {
            object[] results = this.Invoke("KatalogStrediskaDBPrepare", new object[] {
                        idterminal,
                        prefixskladu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogStrediskaDBPrepareAsync(byte idterminal, string prefixskladu) {
            this.KatalogStrediskaDBPrepareAsync(idterminal, prefixskladu, null);
        }
        
        /// <remarks/>
        public void KatalogStrediskaDBPrepareAsync(byte idterminal, string prefixskladu, object userState) {
            if ((this.KatalogStrediskaDBPrepareOperationCompleted == null)) {
                this.KatalogStrediskaDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogStrediskaDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogStrediskaDBPrepare", new object[] {
                        idterminal,
                        prefixskladu}, this.KatalogStrediskaDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogStrediskaDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogStrediskaDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogStrediskaDBPrepareCompleted(this, new KatalogStrediskaDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogPracovniciDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogPracovniciDBPrepare(byte idterminal, string prefixskladu) {
            object[] results = this.Invoke("KatalogPracovniciDBPrepare", new object[] {
                        idterminal,
                        prefixskladu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogPracovniciDBPrepareAsync(byte idterminal, string prefixskladu) {
            this.KatalogPracovniciDBPrepareAsync(idterminal, prefixskladu, null);
        }
        
        /// <remarks/>
        public void KatalogPracovniciDBPrepareAsync(byte idterminal, string prefixskladu, object userState) {
            if ((this.KatalogPracovniciDBPrepareOperationCompleted == null)) {
                this.KatalogPracovniciDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogPracovniciDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogPracovniciDBPrepare", new object[] {
                        idterminal,
                        prefixskladu}, this.KatalogPracovniciDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogPracovniciDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogPracovniciDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogPracovniciDBPrepareCompleted(this, new KatalogPracovniciDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogTypDokladuDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogTypDokladuDBPrepare(byte idterminal, string prefixskladu) {
            object[] results = this.Invoke("KatalogTypDokladuDBPrepare", new object[] {
                        idterminal,
                        prefixskladu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogTypDokladuDBPrepareAsync(byte idterminal, string prefixskladu) {
            this.KatalogTypDokladuDBPrepareAsync(idterminal, prefixskladu, null);
        }
        
        /// <remarks/>
        public void KatalogTypDokladuDBPrepareAsync(byte idterminal, string prefixskladu, object userState) {
            if ((this.KatalogTypDokladuDBPrepareOperationCompleted == null)) {
                this.KatalogTypDokladuDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogTypDokladuDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogTypDokladuDBPrepare", new object[] {
                        idterminal,
                        prefixskladu}, this.KatalogTypDokladuDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogTypDokladuDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogTypDokladuDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogTypDokladuDBPrepareCompleted(this, new KatalogTypDokladuDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogSkladyExport", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusObject KatalogSkladyExport(byte idterminal) {
            object[] results = this.Invoke("KatalogSkladyExport", new object[] {
                        idterminal});
            return ((StatusObject)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogSkladyExportAsync(byte idterminal) {
            this.KatalogSkladyExportAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogSkladyExportAsync(byte idterminal, object userState) {
            if ((this.KatalogSkladyExportOperationCompleted == null)) {
                this.KatalogSkladyExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogSkladyExportOperationCompleted);
            }
            this.InvokeAsync("KatalogSkladyExport", new object[] {
                        idterminal}, this.KatalogSkladyExportOperationCompleted, userState);
        }
        
        private void OnKatalogSkladyExportOperationCompleted(object arg) {
            if ((this.KatalogSkladyExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogSkladyExportCompleted(this, new KatalogSkladyExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogSkladyDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogSkladyDBPrepare(byte idterminal) {
            object[] results = this.Invoke("KatalogSkladyDBPrepare", new object[] {
                        idterminal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogSkladyDBPrepareAsync(byte idterminal) {
            this.KatalogSkladyDBPrepareAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogSkladyDBPrepareAsync(byte idterminal, object userState) {
            if ((this.KatalogSkladyDBPrepareOperationCompleted == null)) {
                this.KatalogSkladyDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogSkladyDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogSkladyDBPrepare", new object[] {
                        idterminal}, this.KatalogSkladyDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogSkladyDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogSkladyDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogSkladyDBPrepareCompleted(this, new KatalogSkladyDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogLokaceDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogLokaceDBPrepare(byte idterminal, string prefixskladu) {
            object[] results = this.Invoke("KatalogLokaceDBPrepare", new object[] {
                        idterminal,
                        prefixskladu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogLokaceDBPrepareAsync(byte idterminal, string prefixskladu) {
            this.KatalogLokaceDBPrepareAsync(idterminal, prefixskladu, null);
        }
        
        /// <remarks/>
        public void KatalogLokaceDBPrepareAsync(byte idterminal, string prefixskladu, object userState) {
            if ((this.KatalogLokaceDBPrepareOperationCompleted == null)) {
                this.KatalogLokaceDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogLokaceDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogLokaceDBPrepare", new object[] {
                        idterminal,
                        prefixskladu}, this.KatalogLokaceDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogLokaceDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogLokaceDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogLokaceDBPrepareCompleted(this, new KatalogLokaceDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogEventTypesDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogEventTypesDBPrepare(byte idterminal) {
            object[] results = this.Invoke("KatalogEventTypesDBPrepare", new object[] {
                        idterminal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogEventTypesDBPrepareAsync(byte idterminal) {
            this.KatalogEventTypesDBPrepareAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogEventTypesDBPrepareAsync(byte idterminal, object userState) {
            if ((this.KatalogEventTypesDBPrepareOperationCompleted == null)) {
                this.KatalogEventTypesDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogEventTypesDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogEventTypesDBPrepare", new object[] {
                        idterminal}, this.KatalogEventTypesDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogEventTypesDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogEventTypesDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogEventTypesDBPrepareCompleted(this, new KatalogEventTypesDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fask.cz/KatalogTiskarnyDBPrepare", RequestNamespace="http://fask.cz/", ResponseNamespace="http://fask.cz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KatalogTiskarnyDBPrepare(byte idterminal) {
            object[] results = this.Invoke("KatalogTiskarnyDBPrepare", new object[] {
                        idterminal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KatalogTiskarnyDBPrepareAsync(byte idterminal) {
            this.KatalogTiskarnyDBPrepareAsync(idterminal, null);
        }
        
        /// <remarks/>
        public void KatalogTiskarnyDBPrepareAsync(byte idterminal, object userState) {
            if ((this.KatalogTiskarnyDBPrepareOperationCompleted == null)) {
                this.KatalogTiskarnyDBPrepareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKatalogTiskarnyDBPrepareOperationCompleted);
            }
            this.InvokeAsync("KatalogTiskarnyDBPrepare", new object[] {
                        idterminal}, this.KatalogTiskarnyDBPrepareOperationCompleted, userState);
        }
        
        private void OnKatalogTiskarnyDBPrepareOperationCompleted(object arg) {
            if ((this.KatalogTiskarnyDBPrepareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KatalogTiskarnyDBPrepareCompleted(this, new KatalogTiskarnyDBPrepareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fask.cz/")]
    public partial class StatusObject {
        
        private string _statusFileField;
        
        private string statusTextField;
        
        private bool exceptionField;
        
        private System.DateTime datumZapisuField;
        
        private bool finishedField;
        
        public StatusObject() {
            this.finishedField = false;
        }
        
        /// <remarks/>
        public string _statusFile {
            get {
                return this._statusFileField;
            }
            set {
                this._statusFileField = value;
            }
        }
        
        /// <remarks/>
        public string StatusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        public bool Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatumZapisu {
            get {
                return this.datumZapisuField;
            }
            set {
                this.datumZapisuField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Finished {
            get {
                return this.finishedField;
            }
            set {
                this.finishedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogZboziExportCompletedEventHandler(object sender, KatalogZboziExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogZboziExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogZboziExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogOdberateleExportCompletedEventHandler(object sender, KatalogOdberateleExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogOdberateleExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogOdberateleExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogStrediskaExportCompletedEventHandler(object sender, KatalogStrediskaExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogStrediskaExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogStrediskaExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogPracovniciExportCompletedEventHandler(object sender, KatalogPracovniciExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogPracovniciExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogPracovniciExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogMenyExportCompletedEventHandler(object sender, KatalogMenyExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogMenyExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogMenyExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogZboziDBPrepareCompletedEventHandler(object sender, KatalogZboziDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogZboziDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogZboziDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogMenyDBPrepareCompletedEventHandler(object sender, KatalogMenyDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogMenyDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogMenyDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogOdberateleDBPrepareCompletedEventHandler(object sender, KatalogOdberateleDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogOdberateleDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogOdberateleDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogStrediskaDBPrepareCompletedEventHandler(object sender, KatalogStrediskaDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogStrediskaDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogStrediskaDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogPracovniciDBPrepareCompletedEventHandler(object sender, KatalogPracovniciDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogPracovniciDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogPracovniciDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogTypDokladuDBPrepareCompletedEventHandler(object sender, KatalogTypDokladuDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogTypDokladuDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogTypDokladuDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogSkladyExportCompletedEventHandler(object sender, KatalogSkladyExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogSkladyExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogSkladyExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogSkladyDBPrepareCompletedEventHandler(object sender, KatalogSkladyDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogSkladyDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogSkladyDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogLokaceDBPrepareCompletedEventHandler(object sender, KatalogLokaceDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogLokaceDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogLokaceDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogEventTypesDBPrepareCompletedEventHandler(object sender, KatalogEventTypesDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogEventTypesDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogEventTypesDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KatalogTiskarnyDBPrepareCompletedEventHandler(object sender, KatalogTiskarnyDBPrepareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KatalogTiskarnyDBPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KatalogTiskarnyDBPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591