ALTER TABLE CZMST092
ADD cfg_sarze_ONOFF [tinyint] NULL DEFAULT 1


ALTER TABLE CZMST092
ADD cfg_sn_ONOFF [tinyint] NULL DEFAULT 1

ALTER TABLE CZMST092
ADD cfg_expirace_ONOFF [tinyint] NULL DEFAULT 1

