using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fask.MST_W_Server.SQLite_Classes
{
    ////In Table Adapter    
    //protected override void Dispose(bool disposing)
    //{
    //    base.Dispose(disposing);
    //    SQLite_Classes.SQLite_Common.DisposeTableAdapter(disposing, this._adapter, this._commandCollection);
    //}

    public static class SQLite_Common
    {
        /// <summary>
        /// Disposes a TableAdapter generated by SQLite Designer
        /// </summary>
        /// <param name="disposing"></param>
        /// <param name="adapter"></param>
        /// <param name="commandCollection"></param>
        /// <remarks>You must dispose all the command,
        /// otherwise the file remains locked and cannot be accessed
        /// (for example, for reading or deletion)</remarks>
        public static void DisposeTableAdapter(
            bool disposing,
            System.Data.SQLite.SQLiteDataAdapter adapter,
            IEnumerable<System.Data.SQLite.SQLiteCommand> commandCollection)
        {
            if (disposing)
            {
                DisposeSQLiteTableAdapter(adapter);

                foreach (var currentCommand_loopVariable in commandCollection)
                {
                    var currentCommand = currentCommand_loopVariable;
                    currentCommand.Dispose();
                }
            }
        }

        public static void DisposeSQLiteTableAdapter(
                System.Data.SQLite.SQLiteDataAdapter adapter)
        {
            if (adapter != null)
            {
                DisposeSQLiteTableAdapterCommands(adapter);

                adapter.Dispose();
            }
        }

        public static void DisposeSQLiteTableAdapterCommands(
                System.Data.SQLite.SQLiteDataAdapter adapter)
        {
            foreach (var currentCommand_loopVariable in new List<object>{
                adapter.UpdateCommand,
                adapter.InsertCommand,
                adapter.DeleteCommand,
                adapter.SelectCommand
            })
            {
                var currentCommand = currentCommand_loopVariable as System.Data.SQLite.SQLiteCommand;
                if (currentCommand != null)
                {
                    currentCommand.Dispose();
                }
            }
        }
    }
}