/****** Object:  Table [dbo].[CZMST_TERMINAL_DEFINITION]   ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CZMST_TERMINAL_DEFINITION](
	[ID_TERMINAL] [int] NOT NULL,
	[DB_TYPE] [nvarchar](10) NOT NULL DEFAULT ('Sqlite'),
 CONSTRAINT [PK_CZMST_TERMINAL_DEFINITION] PRIMARY KEY CLUSTERED 
(
	[ID_TERMINAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/**************************************************************************************/