CREATE TABLE CZMSTPWD
(
  LOGIN Char(20) NOT NULL COLLATE PXW_CSY,
  PASSWD Char(20) NOT NULL COLLATE PXW_CSY,
  ID Integer NOT NULL,
  ADM Smallint,
  FIRSTNAME Char(15) NOT NULL COLLATE PXW_CSY,
  SECONDNAME Char(40) NOT NULL COLLATE PXW_CSY,
  HASH Varchar(128) COLLATE PXW_CSY,
  EAN Char(31) COLLATE PXW_CSY,
  CODE Varchar(5) NOT NULL COLLATE PXW_CSY,
  PRIMARY KEY (ID),
  UNIQUE (LOGIN)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CZMSTPWD TO  SYSDBA WITH GRANT OPTION;

